# CODECOV CONFIGURATION
# https://docs.codecov.com/docs/codecovyml-reference

---
codecov:
  notify:
    after_n_builds: 4
    wait_for_ci: true
  require_ci_to_pass: true

comment:
  after_n_builds: 4
  behavior: default
  layout: header,diff,flags,components,tree,footer
  require_base: false
  require_changes: false
  require_head: true
  show_carryforward_flags: true
  show_critical_paths: true

component_management:
  default_rules:
    statuses:
      - type: project
        target: 100%
  individual_components:
    - component_id: cli
      name: cli
      paths:
        - src/cli/**/*.ts
    - component_id: config
      name: config
      paths:
        - src/config/*.ts
    - component_id: internal
      name: internal
      paths:
        - src/internal/*.ts
    - component_id: plugins
      name: plugins
      paths:
        - src/plugins/**/*.ts
    - component_id: utils
      name: utils
      paths:
        - src/utils/*.ts

coverage:
  precision: 2
  range: 90..100
  round: nearest
  status:
    changes:
      default:
        branches:
          - dependabot/*
          - feat/*
          - hotfix/*
          - main
          - release/*
        if_ci_failed: error
        if_not_found: success
        informational: false
        only_pulls: false
    patch:
      default:
        branches:
          - dependabot/*
          - feat/*
          - hotfix/*
          - main
          - release/*
        if_ci_failed: error
        if_not_found: success
        informational: false
        only_pulls: false
        target: 100%
        threshold: 0%
    project:
      default:
        branches:
          - dependabot/*
          - feat/*
          - hotfix/*
          - main
          - release/*
        if_ci_failed: error
        if_not_found: success
        informational: false
        only_pulls: false
        target: 100%
        threshold: 0%

flags:
  node20:
    carryforward: false
    paths:
      - src/
  node19:
    carryforward: false
    paths:
      - src/
  node18:
    carryforward: false
    paths:
      - src/
  node16:
    carryforward: false
    paths:
      - src/

github_checks:
  annotations: true

ignore:
  - '**/__mocks__/**'
  - '**/__tests__/**'
  - '**/index.ts'
  - '**/interfaces/'
  - '**/types/'
  - src/plugins/**/options.ts

profiling:
  critical_files_paths:
    - src/cli/**/*.ts
    - src/config/*.ts
    - src/internal/create-context.ts
    - src/make.ts
