# CODECOV CONFIGURATION
# https://docs.codecov.com/docs/codecovyml-reference

---
codecov:
  notify:
    after_n_builds: 1
    wait_for_ci: true
  require_ci_to_pass: true

comment:
  after_n_builds: 1
  behavior: default
  layout: header,diff,flags,components,tree,footer
  require_base: false
  require_changes: false
  require_head: true
  show_carryforward_flags: true
  show_critical_paths: true

component_management:
  default_rules:
    statuses:
      - type: project
        target: 100%
  individual_components:
    - component_id: cli
      name: cli
      paths:
        - src/cli/**/*.mts
    - component_id: internal
      name: internal
      paths:
        - src/internal/*.mts
    - component_id: plugins
      name: plugins
      paths:
        - src/plugins/*.mts
    - component_id: utils
      name: utils
      paths:
        - src/utils/*.mts

coverage:
  precision: 2
  range: 90..100
  round: nearest
  status:
    changes:
      default:
        branches:
          - dependabot/*
          - feat/*
          - hotfix/*
          - main
          - release/*
        if_ci_failed: error
        if_not_found: success
        informational: false
        only_pulls: false
    patch:
      default:
        branches:
          - dependabot/*
          - feat/*
          - hotfix/*
          - main
          - release/*
        if_ci_failed: error
        if_not_found: success
        informational: false
        only_pulls: false
        target: 100%
        threshold: 0%
    project:
      default:
        branches:
          - dependabot/*
          - feat/*
          - hotfix/*
          - main
          - release/*
        if_ci_failed: error
        if_not_found: success
        informational: false
        only_pulls: false
        target: 100%
        threshold: 0%

flags:
  node23:
    carryforward: false
    paths:
      - src/

github_checks:
  annotations: true

ignore:
  - '**/*.d.mts'
  - '**/__mocks__/'
  - '**/__tests__/'
  - '**/index.mts'
  - '**/interfaces/'
  - '**/types/'
  - '!src/index.mts'
  - src/internal/*.browser.mts

profiling:
  critical_files_paths:
    - src/cli/**/*.mts
    - src/make.mts
    - src/plugins/*.mts
    - src/utils/load-build-config.mts
    - src/utils/runnable-task.mts
