/**
 * @file Type Definitions - GeneratedFileType
 * @module mkbuild/types/GeneratedFileType
 */

/**
 * File types generated by esbuild.
 */
type GeneratedFileType = 'css' | 'js'

export type { GeneratedFileType as default }
