/**
 * @file Interfaces - RollupCodeMap
 * @module mkbuild/interfaces/RollupCodeMap
 */

/**
 * Registry of rollup log codes.
 *
 * @see https://github.com/rollup/rollup/blob/master/src/utils/logs.ts
 */
interface RollupCodeMap {
  ADDON_ERROR: true
  ALREADY_CLOSED: true
  AMBIGUOUS_EXTERNAL_NAMESPACES: true
  ANONYMOUS_PLUGIN_CACHE: true
  ASSET_NOT_FINALISED: true
  ASSET_NOT_FOUND: true
  ASSET_SOURCE_ALREADY_SET: true
  ASSET_SOURCE_MISSING: true
  BAD_LOADER: true
  CANNOT_CALL_NAMESPACE: true
  CANNOT_EMIT_FROM_OPTIONS_HOOK: true
  CHUNK_INVALID: true
  CHUNK_NOT_GENERATED: true
  CIRCULAR_DEPENDENCY: true
  CIRCULAR_REEXPORT: true
  CONST_REASSIGN: true
  CYCLIC_CROSS_CHUNK_REEXPORT: true
  DEPRECATED_FEATURE: true
  DUPLICATE_ARGUMENT_NAME: true
  DUPLICATE_EXPORT: true
  DUPLICATE_IMPORT_OPTIONS: true
  DUPLICATE_PLUGIN_NAME: true
  EMPTY_BUNDLE: true
  EVAL: true
  EXTERNAL_MODULES_CANNOT_BE_INCLUDED_IN_MANUAL_CHUNKS: true
  EXTERNAL_MODULES_CANNOT_BE_TRANSFORMED_TO_MODULES: true
  EXTERNAL_SYNTHETIC_EXPORTS: true
  FAIL_AFTER_WARNINGS: true
  FILE_NAME_CONFLICT: true
  FILE_NOT_FOUND: true
  FIRST_SIDE_EFFECT: true
  ILLEGAL_IDENTIFIER_AS_NAME: true
  ILLEGAL_REASSIGNMENT: true
  INCONSISTENT_IMPORT_ATTRIBUTES: true
  INPUT_HOOK_IN_OUTPUT_PLUGIN: true
  INVALID_ANNOTATION: true
  INVALID_CHUNK: true
  INVALID_CONFIG_MODULE_FORMAT: true
  INVALID_EXPORT_OPTION: true
  INVALID_EXTERNAL_ID: true
  INVALID_IMPORT_ATTRIBUTE: true
  INVALID_LOG_POSITION: true
  INVALID_OPTION: true
  INVALID_PLUGIN_HOOK: true
  INVALID_ROLLUP_PHASE: true
  INVALID_SETASSETSOURCE: true
  INVALID_TLA_FORMAT: true
  MISSING_CONFIG: true
  MISSING_EXPORT: true
  MISSING_EXTERNAL_CONFIG: true
  MISSING_GLOBAL_NAME: true
  MISSING_IMPLICIT_DEPENDANT: true
  MISSING_JSX_EXPORT: true
  MISSING_NAME_OPTION_FOR_IIFE_EXPORT: true
  MISSING_NODE_BUILTINS: true
  MISSING_OPTION: true
  MIXED_EXPORTS: true
  MODULE_LEVEL_DIRECTIVE: true
  NAMESPACE_CONFLICT: true
  NO_FS_IN_BROWSER: true
  NO_TRANSFORM_MAP_OR_AST_WITHOUT_CODE: true
  ONLY_INLINE_SOURCEMAPS: true
  OPTIMIZE_CHUNK_STATUS: true
  PARSE_ERROR: true
  PLUGIN_ERROR: true
  PLUGIN_LOG: true
  PLUGIN_WARNING: true
  REDECLARATION_ERROR: true
  RESERVED_NAMESPACE: true
  SHIMMED_EXPORT: true
  SOURCEMAP_BROKEN: true
  SOURCEMAP_ERROR: true
  SYNTHETIC_NAMED_EXPORTS_NEED_NAMESPACE_EXPORT: true
  THIS_IS_UNDEFINED: true
  UNEXPECTED_NAMED_IMPORT: true
  UNKNOWN_OPTION: true
  UNRESOLVED_ENTRY: true
  UNRESOLVED_IMPORT: true
  UNUSED_EXTERNAL_IMPORT: true
  VALIDATION_ERROR: true
}

export type { RollupCodeMap as default }
